### ISSUE TITLE
SFTP file upload

### ISSUE THREAD

**Issue by jonferreira** [HardingPoint/node-red-contrib-ftp-sftp#1]
Hi,

So one can't upload a file then? Only "write" a string content to a remote file?

**Comment by gaskaj** [comment]
Good Morning;

We wrote it this way as the cloud vendor it typically runs on uses an ephemeral file system. You would simply read the file (using many of the readfile nodes) and set the string. There were a few other FTP/SFTP nodes that did do what you were looking for but we opted to simplify and read file before calling FTP.

msg.payload = {};
msg.payload.filename="./SAMPLE_FILE.txt"; // Full Path
msg.payload.filedata='{}'; // Needs to be a string
return msg;

If you would like to update and validate it doing what you need happy to review and commit.  Please let me know if you have any questions.

**Comment by jonferreira** [comment]
I'd be using this to upload sqlite DB's so would be great if it could take a file path and upload it

**Comment by gaskaj** [comment]
Can you do me a favor and try using the file node and then mapping the output from that node in a script node like below and then pass in to the FTP/SFTP node see if it works. It "should" work as expected but memory may be an issue depending on the size of the database files. Would need a sample file to validate but I am thinking something like below should work for you.

newmsg = {};
newmsg.payload = {};
newmsg.payload.filename="./SAMPLE_FILE.txt"; // Full Path
newmsg.payload.filedata=msg.payload;
return newmsg

![image](https://user-images.githubusercontent.com/833726/37405425-f434b7d0-276a-11e8-92eb-13b3fb2fded2.png)

**Comment by gaskaj** [comment]
Looking at the code PUT should work fine but FTP GET might not work for Binary files (would need someone to confirm). I believe SFTP PUT/GET should be fine the way the binary buffer is handled. Again, try it out let me know. Best of luck.

**Comment by jonferreira** [comment]
OK will give it a try later today although it seems a bit of a waste of resources, especially with larger files

**Comment by gaskaj** [comment]
Whether the read file / stream is in the JS for the FTP or the read file / stream is in a file object it is in essence the same resource consumption/usage. You still need to pull data and chunk to push into stream. Simply trying to help you solve this right now as the FTP node is meant to focus 100% on FTP and SFTP and allow others to read data from any source (file, HTTP, HTTPS, SAP, CRM, etc++) and send. If we solved for every source then would eliminate value. Seems like a waste of time for me to reinvent wheel... Again, just trying to help as best we can.

**Comment by jonferreira** [comment]
I've triedit today but unfortunately, while it works OK with a 1mb jpeg it seems to crash node-red with a 44mb DB.

No usefull output whatsoever, just after a 5min wait or so:

Mar 16 14:54:23 raspberrypi systemd[1]: nodered.service: main process exited, code=killed, status=9/KILL
Mar 16 14:54:23 raspberrypi systemd[1]: Unit nodered.service entered failed state.

**Comment by gaskaj** [comment]
Are you using the FTP or SFTP node? We did change the default stream buffer/chunk size for another issue. Happy to help you get this working. Let me know.

**Comment by gaskaj** [comment]
Jon;

Can we mark this closed? Did you get everything to work as expected?

Thanks
-Joe

**Comment by jonferreira** [comment]
Hi Joe,

Sorry, I've missed your previous message. I was using the SFTP node.

I ended up going the lazy way and coded my own node-red SFTP node - https://github.com/jonferreira/node-red-contrib-sftp

Thanks for the help
