### ISSUE TITLE
https://github.com/HardingPoint/jsftp  404

### ISSUE THREAD

**Issue by sragneau** [HardingPoint/node-red-contrib-ftp-sftp#3]
Package.json must be updated to get JSFTP with an other url.

**Comment by gaskaj** [comment]
Apologies, think that reference was archived by mistake. Will take care of this in a few hours and let you know.

**Comment by vjoshihumancare** [comment]
hi any updates on this ?

**Comment by TyTheDev** [comment]
Looks like the Node-RED package manager is still using the old package files. Any plans to fix this, or any tips for getting around it?

**Comment by gaskaj** [comment]
My apologies team did not publish update to NPM. Can you all please test now let me know if you have any issues.

**Comment by TyTheDev** [comment]
Looks good. Thanks!

**Comment by gaskaj** [comment]
Great, let me know if you have any issues. Going to close this out.
