### ISSUE TITLE
issues installing 

### ISSUE THREAD

**Issue by jhaaken-ibm** [HardingPoint/node-red-contrib-ftp-sftp#4]
I am logged into GitHub, however, a clean install or an update doesn't work.  I was able to install 1.7 just can't get to 1.8.  It prompts for userid/pswd and rejects it as invalid.

Any thoughts?

`PS C:\Users\IBM_ADMIN\.node-red> npm update node-red-contrib-ftp-sftp
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/HardingPoint/jsftp.git
npm ERR!
npm ERR! fatal: HttpRequestException encountered.
npm ERR!    An error occurred while sending the request.
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/HardingPoint/jsftp.git/'
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\_logs\2018-10-05T16_03_48_173Z-debug.log`

**Comment by gaskaj** [comment]
My apologies team did not publish update to NPM. Can you all please test now let me know if you have any issues.

**Comment by gaskaj** [comment]
Should be good now, please reopen if you have any issues.
