### ISSUE TITLE
Q: SFTP file dowload using msg.xxx

### ISSUE THREAD

**Issue by azrin1972** [HardingPoint/node-red-contrib-ftp-sftp#5]
Hi,
How to I get a file and put onto a different working directory adn different name using msg.filename

something like 'get /public/filename.txt /opt/alternate_filename.txt'

**Comment by elvissouza** [comment]
Solution ???

**Comment by elvissouza** [comment]
My Solution, install node-red-contrib-sftp and pass msg.remoteFilePath
