### ISSUE TITLE
Error handling with sftp/ftp node

### ISSUE THREAD

**Issue by jignesht24** [HardingPoint/node-red-contrib-ftp-sftp#7]
How can we do the error handling with sftp/ftp node. If sftp/ftp is not available, is this node raised error?

**Comment by gaskaj** [comment]
It should have been but feel free to submit a PR if you want to modify the code I will accept it. I have not modified this in a long time as I originally wrote for a client that was using SFTP and it is still in use.

**Comment by jignesht24** [comment]
SFTP is working fine for me but in case of sftp is not available or incorrect credential, error is not catch by "CATCH" node as node.error does not sent original message.
I want "node.error(err,msg)" change instead of  "node.error(err)"

Thanks

**Comment by HenryNe** [comment]
Fixed
