### ISSUE TITLE
what is hmac and cipher?

### ISSUE THREAD

**Issue by ricardo2312** [HardingPoint/node-red-contrib-ftp-sftp#8]
what is hmac and cipher? where can i find those paremeters?

**Comment by hammeronthenet** [comment]
I need that explanation too. :)

**Comment by gaskaj** [comment]
https://github.com/gaskaj/node-red-contrib-ftp-sftp/blob/b82bb85672ca796c1e509e61c47a0187631ee0c7/sftp.js#L71
